export const dashboardData = {
  stats: {
    totalDatabases: 127,
    activeUsers: 2847,
    pendingRequests: 34,
    securityAlerts: 12,
    privilegedAccounts: 186,
    failedLogins: 248,
  },

  databaseDistribution: [
    { name: 'PostgreSQL', value: 54, fill: '#3b82f6' },
    { name: 'MySQL', value: 38, fill: '#10b981' },
    { name: 'MongoDB', value: 21, fill: '#f59e0b' },
    { name: 'Oracle', value: 9, fill: '#ef4444' },
    { name: 'SQL Server', value: 5, fill: '#8b5cf6' },
  ],

  storageData: [
    { name: 'PostgreSQL', value: 4.8 },
    { name: 'MySQL', value: 2.9 },
    { name: 'MongoDB', value: 3.4 },
    { name: 'Oracle', value: 1.2 },
    { name: 'SQL Server', value: 0.8 },
  ],

  queryActivity: [
    { date: 'Mon', queries: 1.2 },
    { date: 'Tue', queries: 1.4 },
    { date: 'Wed', queries: 1.1 },
    { date: 'Thu', queries: 1.8 },
    { date: 'Fri', queries: 2.3 },
    { date: 'Sat', queries: 1.6 },
    { date: 'Sun', queries: 1.3 },
  ],

  accessRequests: [
    { date: 'Day 1', approved: 45, rejected: 8, pending: 12 },
    { date: 'Day 5', approved: 52, rejected: 10, pending: 15 },
    { date: 'Day 10', approved: 68, rejected: 12, pending: 18 },
    { date: 'Day 15', approved: 85, rejected: 15, pending: 22 },
    { date: 'Day 20', approved: 102, rejected: 18, pending: 28 },
    { date: 'Day 25', approved: 125, rejected: 22, pending: 32 },
    { date: 'Day 30', approved: 148, rejected: 25, pending: 34 },
  ],

  failedLogins: [
    { date: 'Mon', attempts: 32 },
    { date: 'Tue', attempts: 28 },
    { date: 'Wed', attempts: 45 },
    { date: 'Thu', attempts: 38 },
    { date: 'Fri', attempts: 52 },
    { date: 'Sat', attempts: 18 },
    { date: 'Sun', attempts: 24 },
  ],

  databaseInventory: [
    {
      name: 'CustomerDB',
      type: 'PostgreSQL',
      environment: 'Production',
      owner: 'Finance Team',
      storage: '850GB',
      activeUsers: 412,
      health: 'Healthy',
    },
    {
      name: 'OrdersDB',
      type: 'MySQL',
      environment: 'Production',
      owner: 'Sales Team',
      storage: '640GB',
      activeUsers: 328,
      health: 'Healthy',
    },
    {
      name: 'AnalyticsDB',
      type: 'MongoDB',
      environment: 'Production',
      owner: 'Analytics Team',
      storage: '1.4TB',
      activeUsers: 228,
      health: 'Warning',
    },
    {
      name: 'HRDB',
      type: 'PostgreSQL',
      environment: 'Production',
      owner: 'HR Team',
      storage: '320GB',
      activeUsers: 87,
      health: 'Healthy',
    },
    {
      name: 'LegacyERP',
      type: 'Oracle',
      environment: 'Production',
      owner: 'Operations Team',
      storage: '980GB',
      activeUsers: 54,
      health: 'Critical',
    },
  ],

  healthMonitoring: [
    {
      name: 'PostgreSQL Cluster',
      cpu: 62,
      memory: 71,
      disk: 58,
      status: 'Healthy',
    },
    {
      name: 'MySQL Cluster',
      cpu: 54,
      memory: 67,
      disk: 49,
      status: 'Healthy',
    },
    {
      name: 'MongoDB Cluster',
      cpu: 83,
      memory: 76,
      disk: 69,
      status: 'Warning',
    },
    {
      name: 'Oracle Cluster',
      cpu: 91,
      memory: 88,
      disk: 80,
      status: 'Critical',
    },
  ],

  securityMetrics: {
    privilegedAccessRequests: 56,
    unauthorizedAttempts: 18,
    suspiciousQueries: 7,
    policyViolations: 13,
    dataExfiltrationAlerts: 2,
    trend: [
      { date: 'Day 1', violations: 5 },
      { date: 'Day 5', violations: 8 },
      { date: 'Day 10', violations: 12 },
      { date: 'Day 15', violations: 10 },
      { date: 'Day 20', violations: 15 },
      { date: 'Day 25', violations: 13 },
      { date: 'Day 30', violations: 13 },
    ],
  },

  auditActivities: [
    {
      time: '10:23 AM',
      action: 'Access Requested',
      user: 'John Smith',
      resource: 'PostgreSQL production',
      type: 'request',
    },
    {
      time: '10:18 AM',
      action: 'Backup Completed',
      user: 'System',
      resource: 'OrdersDB',
      type: 'success',
    },
    {
      time: '10:11 AM',
      action: 'Database Registered',
      user: 'Admin',
      resource: 'New MongoDB instance',
      type: 'info',
    },
    {
      time: '09:54 AM',
      action: 'Policy Violation',
      user: 'Unknown',
      resource: 'OracleDB',
      type: 'warning',
    },
    {
      time: '09:43 AM',
      action: 'Access Approved',
      user: 'Security Admin',
      resource: 'Analytics Team',
      type: 'success',
    },
    {
      time: '09:30 AM',
      action: 'Failed Login Attempt',
      user: 'test@example.com',
      resource: 'Admin Portal',
      type: 'error',
    },
    {
      time: '09:15 AM',
      action: 'Configuration Changed',
      user: 'DBA',
      resource: 'MySQL settings',
      type: 'info',
    },
    {
      time: '09:00 AM',
      action: 'Compliance Check',
      user: 'Auditor',
      resource: 'All databases',
      type: 'success',
    },
  ],

  infrastructureOverview: [
    {
      platform: 'PostgreSQL',
      databases: 54,
      storage: '4.8 TB',
      connections: 1245,
    },
    {
      platform: 'MySQL',
      databases: 38,
      storage: '2.9 TB',
      connections: 854,
    },
    {
      platform: 'MongoDB',
      databases: 21,
      storage: '3.4 TB',
      connections: 631,
    },
    {
      platform: 'Oracle',
      databases: 9,
      storage: '1.2 TB',
      connections: 203,
    },
    {
      platform: 'SQL Server',
      databases: 5,
      storage: '0.8 TB',
      connections: 98,
    },
  ],
}
