export const userDamDashboardData = {
  topStats: [
    { label: 'Accessible Databases', value: 12, subtitle: 'Databases available to this user', icon: 'database' },
    { label: 'Active Sessions', value: 3, subtitle: 'Currently connected sessions', icon: 'activity' },
    { label: 'Assigned Roles', value: 5, subtitle: 'Active permission roles', icon: 'shield' },
    { label: 'Pending Requests', value: 2, subtitle: 'Awaiting approval', icon: 'clock' },
    { label: 'Security Score', value: '92%', subtitle: 'Account security health', icon: 'check' },
    { label: 'Last Login', value: 'Today, 09:34 AM', subtitle: 'Most recent successful login', icon: 'login' },
  ],

  accessibleDatabases: [
    {
      id: '1',
      name: 'CustomerDB',
      type: 'PostgreSQL',
      environment: 'Production',
      accessLevel: 'Read Only',
      storageUsed: '450 GB',
      lastAccessed: '2 Hours Ago',
      status: 'Active',
      icon: 'postgres',
    },
    {
      id: '2',
      name: 'AnalyticsDB',
      type: 'MySQL',
      environment: 'Development',
      accessLevel: 'Read/Write',
      storageUsed: '220 GB',
      lastAccessed: 'Today',
      status: 'Active',
      icon: 'mysql',
    },
    {
      id: '3',
      name: 'InventoryDB',
      type: 'MongoDB',
      environment: 'Staging',
      accessLevel: 'Admin',
      storageUsed: '175 GB',
      lastAccessed: 'Yesterday',
      status: 'Active',
      icon: 'mongodb',
    },
    {
      id: '4',
      name: 'BillingDB',
      type: 'PostgreSQL',
      environment: 'Production',
      accessLevel: 'Read Only',
      storageUsed: '310 GB',
      lastAccessed: '3 Days Ago',
      status: 'Active',
      icon: 'postgres',
    },
    {
      id: '5',
      name: 'LogsDB',
      type: 'Elasticsearch',
      environment: 'Production',
      accessLevel: 'Read',
      storageUsed: '120 GB',
      lastAccessed: 'Today',
      status: 'Active',
      icon: 'elasticsearch',
    },
  ],

  accessRequests: [
    {
      id: 'AR-001',
      database: 'BillingDB',
      requestedAccess: 'Read/Write',
      requestDate: '2024-12-01',
      duration: '30 days',
      status: 'Pending',
      approver: 'John Smith',
    },
    {
      id: 'AR-002',
      database: 'ReportsDB',
      requestedAccess: 'Admin',
      requestDate: '2024-11-28',
      duration: '60 days',
      status: 'Approved',
      approver: 'Jane Doe',
    },
  ],

  activeSessions: [
    {
      id: 'S-001',
      database: 'CustomerDB',
      startTime: '09:34 AM',
      duration: '2h 15m',
      device: 'MacBook Pro',
      ipAddress: '192.168.1.100',
      location: 'New York, USA',
      status: 'Active',
    },
    {
      id: 'S-002',
      database: 'AnalyticsDB',
      startTime: '10:12 AM',
      duration: '1h 47m',
      device: 'Windows Desktop',
      ipAddress: '192.168.1.101',
      location: 'New York, USA',
      status: 'Active',
    },
    {
      id: 'S-003',
      database: 'LogsDB',
      startTime: '08:45 AM',
      duration: '3h 24m',
      device: 'Linux Server',
      ipAddress: '10.0.0.50',
      location: 'Cloud Datacenter',
      status: 'Active',
    },
  ],

  userRoles: [
    {
      id: 'R-001',
      name: 'Database Analyst',
      assignedDate: '2024-06-15',
      expiryDate: '2025-06-15',
      permissions: [
        'Read Customer Data',
        'Execute Reports',
        'Export Reports',
      ],
    },
    {
      id: 'R-002',
      name: 'Database Developer',
      assignedDate: '2024-01-10',
      expiryDate: '2025-01-10',
      permissions: [
        'Create Tables',
        'Modify Schemas',
        'Execute Stored Procedures',
        'Deploy Changes',
      ],
    },
    {
      id: 'R-003',
      name: 'Audit Viewer',
      assignedDate: '2024-09-01',
      expiryDate: '2025-09-01',
      permissions: [
        'Access Audit Logs',
        'View Compliance Reports',
        'Export Audit Data',
      ],
    },
  ],

  securityCenter: {
    score: 92,
    checks: [
      { name: 'MFA Enabled', status: true },
      { name: 'Trusted Device Registered', status: true },
      { name: 'Password Policy Compliant', status: true },
      { name: 'Secure Login Enabled', status: true },
      { name: 'Session Encryption Active', status: true },
    ],
    warnings: [
      { message: 'Password expires in 18 days', severity: 'warning' },
    ],
  },

  activityAnalytics: {
    weeklyAccess: [
      { day: 'Mon', value: 45 },
      { day: 'Tue', value: 52 },
      { day: 'Wed', value: 48 },
      { day: 'Thu', value: 61 },
      { day: 'Fri', value: 55 },
      { day: 'Sat', value: 22 },
      { day: 'Sun', value: 18 },
    ],
    monthlyQueries: [
      { month: 'Jan', value: 2400 },
      { month: 'Feb', value: 2210 },
      { month: 'Mar', value: 2290 },
      { month: 'Apr', value: 2000 },
      { month: 'May', value: 2181 },
      { month: 'Jun', value: 2500 },
    ],
    databaseUsage: [
      { name: 'CustomerDB', value: 35 },
      { name: 'AnalyticsDB', value: 25 },
      { name: 'InventoryDB', value: 18 },
      { name: 'BillingDB', value: 15 },
      { name: 'LogsDB', value: 7 },
    ],
    accessTrends: [
      { week: 'Week 1', approved: 8, rejected: 1, pending: 2 },
      { week: 'Week 2', approved: 6, rejected: 0, pending: 1 },
      { week: 'Week 3', approved: 9, rejected: 2, pending: 3 },
      { week: 'Week 4', approved: 7, rejected: 1, pending: 2 },
    ],
  },

  recentActivity: [
    { time: '09:34 AM', action: 'Logged into CustomerDB', icon: 'login', type: 'login' },
    { time: '10:12 AM', action: 'Generated Sales Analytics Report', icon: 'report', type: 'report' },
    { time: '11:02 AM', action: 'Requested Access to BillingDB', icon: 'request', type: 'request' },
    { time: '11:15 AM', action: 'Approval Granted', icon: 'check', type: 'approval' },
    { time: '12:45 PM', action: 'Exported Data Summary', icon: 'export', type: 'export' },
    { time: '02:30 PM', action: 'Updated Profile Settings', icon: 'settings', type: 'settings' },
  ],

  performanceInsights: [
    { label: 'Average Query Time', value: '145 ms', change: '-8%', trend: 'down' },
    { label: 'Queries Executed Today', value: '3,421', change: '+12%', trend: 'up' },
    { label: 'Data Accessed Today', value: '4.2 GB', change: '+5%', trend: 'up' },
    { label: 'Failed Queries', value: '12', change: '-3%', trend: 'down' },
    { label: 'Most Active Database', value: 'CustomerDB', change: 'Stable', trend: 'stable' },
    { label: 'Storage Utilization', value: '68%', change: '+2%', trend: 'up' },
  ],

  notifications: [
    { id: '1', title: 'Access Request Approved', message: 'Your access request for BillingDB has been approved', read: false, type: 'success' },
    { id: '2', title: 'Database Maintenance Scheduled', message: 'CustomerDB maintenance on 2024-12-10 from 2-4 AM', read: false, type: 'info' },
    { id: '3', title: 'Security Alert', message: 'New login detected from unknown location', read: true, type: 'warning' },
    { id: '4', title: 'Password Expiry Reminder', message: 'Your password expires in 18 days', read: true, type: 'warning' },
    { id: '5', title: 'Role Updated', message: 'Database Developer role has been extended', read: true, type: 'info' },
    { id: '6', title: 'New Database Available', message: 'ReportingDB is now available for access requests', read: true, type: 'success' },
  ],

  auditLogs: [
    { timestamp: '2024-12-04 09:34', action: 'Login Success', database: 'CustomerDB', result: 'Success', ipAddress: '192.168.1.100', device: 'MacBook Pro' },
    { timestamp: '2024-12-04 10:12', action: 'Data Export', database: 'AnalyticsDB', result: 'Success', ipAddress: '192.168.1.100', device: 'MacBook Pro' },
    { timestamp: '2024-12-04 11:02', action: 'Access Request', database: 'BillingDB', result: 'Pending', ipAddress: '192.168.1.100', device: 'MacBook Pro' },
    { timestamp: '2024-12-04 14:30', action: 'Query Execution', database: 'CustomerDB', result: 'Success', ipAddress: '192.168.1.100', device: 'MacBook Pro' },
    { timestamp: '2024-12-03 16:45', action: 'Permission Update', database: 'LogsDB', result: 'Success', ipAddress: '192.168.1.100', device: 'MacBook Pro' },
  ],

  userProfile: {
    name: 'John Anderson',
    employeeId: 'EMP-2024-001',
    department: 'Data Analytics',
    designation: 'Senior Data Analyst',
    email: 'john.anderson@company.com',
    phone: '+1 (555) 123-4567',
    lastLogin: 'Today, 09:34 AM',
    status: 'Active',
    avatar: 'JA',
  },
}
