// Complete User Portal Mock Data

export const userPortalData = {
  // MY DATABASES PAGE
  myDatabases: {
    stats: {
      total: 12,
      production: 5,
      development: 4,
      staging: 3,
    },
    databases: [
      {
        id: 'db-001',
        name: 'CustomerDB',
        type: 'PostgreSQL',
        environment: 'Production',
        accessLevel: 'Read Only',
        hostServer: 'prod-db-01.internal',
        storageSize: '450 GB',
        lastAccessed: '2 Hours Ago',
        status: 'Active',
        connections: 42,
        queryCount: 1245,
      },
      {
        id: 'db-002',
        name: 'AnalyticsDB',
        type: 'MySQL',
        environment: 'Development',
        accessLevel: 'Read/Write',
        hostServer: 'dev-db-02.internal',
        storageSize: '220 GB',
        lastAccessed: 'Today',
        status: 'Active',
        connections: 18,
        queryCount: 456,
      },
      {
        id: 'db-003',
        name: 'InventoryDB',
        type: 'MongoDB',
        environment: 'Staging',
        accessLevel: 'Admin',
        hostServer: 'staging-db-03.internal',
        storageSize: '175 GB',
        lastAccessed: 'Yesterday',
        status: 'Active',
        connections: 25,
        queryCount: 789,
      },
      {
        id: 'db-004',
        name: 'BillingDB',
        type: 'PostgreSQL',
        environment: 'Production',
        accessLevel: 'Read Only',
        hostServer: 'prod-db-04.internal',
        storageSize: '310 GB',
        lastAccessed: '3 Days Ago',
        status: 'Active',
        connections: 35,
        queryCount: 2103,
      },
      {
        id: 'db-005',
        name: 'LogsDB',
        type: 'Elasticsearch',
        environment: 'Production',
        accessLevel: 'Read',
        hostServer: 'prod-db-05.internal',
        storageSize: '120 GB',
        lastAccessed: 'Today',
        status: 'Active',
        connections: 52,
        queryCount: 5421,
      },
    ],
    usageDistribution: [
      { name: 'CustomerDB', value: 35 },
      { name: 'AnalyticsDB', value: 20 },
      { name: 'InventoryDB', value: 18 },
      { name: 'BillingDB', value: 17 },
      { name: 'LogsDB', value: 10 },
    ],
    weeklyTrend: [
      { day: 'Mon', accesses: 45 },
      { day: 'Tue', accesses: 52 },
      { day: 'Wed', accesses: 48 },
      { day: 'Thu', accesses: 61 },
      { day: 'Fri', accesses: 55 },
      { day: 'Sat', accesses: 22 },
      { day: 'Sun', accesses: 18 },
    ],
  },

  // ACCESS REQUESTS PAGE
  accessRequests: {
    stats: {
      total: 8,
      pending: 2,
      approved: 5,
      rejected: 1,
    },
    requests: [
      {
        id: 'AR-001',
        database: 'BillingDB',
        requestedRole: 'Read/Write',
        requestedDuration: '30 days',
        submissionDate: '2024-12-01',
        status: 'Pending',
        approvedBy: 'Pending',
        businessJustification: 'Need to update billing records for Q4',
        projectName: 'Q4 Financial Closing',
        managerApproval: 'John Smith',
      },
      {
        id: 'AR-002',
        database: 'AnalyticsDB',
        requestedRole: 'Admin',
        requestedDuration: '60 days',
        submissionDate: '2024-11-28',
        status: 'Approved',
        approvedBy: 'Jane Doe',
        businessJustification: 'Schema changes for new analytics pipeline',
        projectName: 'Analytics Upgrade',
        managerApproval: 'Mike Johnson',
      },
      {
        id: 'AR-003',
        database: 'CustomerDB',
        requestedRole: 'Read Only',
        requestedDuration: '90 days',
        submissionDate: '2024-11-15',
        status: 'Approved',
        approvedBy: 'Sarah Wilson',
        businessJustification: 'Customer data analysis for report',
        projectName: 'Customer Analytics',
        managerApproval: 'Lisa Brown',
      },
      {
        id: 'AR-004',
        database: 'InventoryDB',
        requestedRole: 'Read/Write',
        requestedDuration: '45 days',
        submissionDate: '2024-11-10',
        status: 'Rejected',
        approvedBy: 'Tom Harris',
        businessJustification: 'Update inventory records',
        projectName: 'Inventory Update',
        managerApproval: 'David Lee',
      },
    ],
  },

  // ACTIVE SESSIONS PAGE
  activeSessions: {
    stats: {
      activeSessions: 3,
      avgSessionTime: '2h 45m',
      activeDevices: 2,
      currentConnections: 47,
    },
    sessions: [
      {
        id: 'SES-001',
        database: 'CustomerDB',
        loginTime: '09:34 AM',
        duration: '2h 15m',
        device: 'MacBook Pro',
        ipAddress: '192.168.1.100',
        location: 'New York, USA',
        status: 'Active',
        queries: 145,
      },
      {
        id: 'SES-002',
        database: 'AnalyticsDB',
        loginTime: '10:12 AM',
        duration: '1h 47m',
        device: 'Windows Desktop',
        ipAddress: '192.168.1.101',
        location: 'New York, USA',
        status: 'Active',
        queries: 62,
      },
      {
        id: 'SES-003',
        database: 'LogsDB',
        loginTime: '08:45 AM',
        duration: '3h 24m',
        device: 'Linux Server',
        ipAddress: '10.0.0.50',
        location: 'Cloud Datacenter',
        status: 'Active',
        queries: 421,
      },
    ],
    activityTrend: [
      { time: '08:00', sessions: 2 },
      { time: '09:00', sessions: 3 },
      { time: '10:00', sessions: 4 },
      { time: '11:00', sessions: 5 },
      { time: '12:00', sessions: 4 },
      { time: '13:00', sessions: 3 },
    ],
    connectionDistribution: [
      { name: 'CustomerDB', value: 42 },
      { name: 'AnalyticsDB', value: 18 },
      { name: 'LogsDB', value: 52 },
      { name: 'InventoryDB', value: 25 },
      { name: 'BillingDB', value: 35 },
    ],
  },

  // ROLES & PERMISSIONS PAGE
  rolesAndPermissions: [
    {
      id: 'role-001',
      name: 'Database Analyst',
      assignmentDate: '2024-06-15',
      expiryDate: '2025-06-15',
      accessScope: ['CustomerDB', 'AnalyticsDB', 'BillingDB'],
      permissions: {
        read: true,
        write: false,
        delete: false,
        export: true,
        admin: false,
      },
      description: 'Analyze customer and billing data',
    },
    {
      id: 'role-002',
      name: 'Database Developer',
      assignmentDate: '2024-01-10',
      expiryDate: '2025-01-10',
      accessScope: ['AnalyticsDB', 'InventoryDB'],
      permissions: {
        read: true,
        write: true,
        delete: false,
        export: true,
        admin: false,
      },
      description: 'Develop and maintain database schemas',
    },
    {
      id: 'role-003',
      name: 'Audit Viewer',
      assignmentDate: '2024-09-01',
      expiryDate: '2025-09-01',
      accessScope: ['CustomerDB', 'BillingDB', 'LogsDB'],
      permissions: {
        read: true,
        write: false,
        delete: false,
        export: true,
        admin: false,
      },
      description: 'Review audit logs and compliance reports',
    },
  ],

  // SECURITY CENTER PAGE
  securityCenter: {
    overallScore: 92,
    widgets: [
      { name: 'MFA Status', status: 'Enabled', icon: 'check' },
      { name: 'Password Health', status: 'Strong', icon: 'check' },
      { name: 'Device Trust', status: '2 Trusted', icon: 'check' },
      { name: 'Encryption Status', status: 'Active', icon: 'check' },
      { name: 'Login Security', status: 'Secured', icon: 'check' },
    ],
    timeline: [
      { time: '09:34 AM', event: 'Successful Login', type: 'login', device: 'MacBook Pro' },
      { time: '14:22 PM', event: 'Password Changed', type: 'password', device: '-' },
      { time: 'Yesterday', event: 'Device Registered', type: 'device', device: 'Windows Desktop' },
      { time: '2 Days Ago', event: 'Failed Login Attempt', type: 'alert', device: 'Unknown' },
    ],
    scoreTrend: [
      { month: 'Aug', score: 85 },
      { month: 'Sep', score: 88 },
      { month: 'Oct', score: 90 },
      { month: 'Nov', score: 91 },
      { month: 'Dec', score: 92 },
    ],
    loginActivityTrend: [
      { day: 'Mon', successful: 12, failed: 1 },
      { day: 'Tue', successful: 15, failed: 0 },
      { day: 'Wed', successful: 14, failed: 1 },
      { day: 'Thu', successful: 18, failed: 2 },
      { day: 'Fri', successful: 16, failed: 1 },
      { day: 'Sat', successful: 5, failed: 0 },
      { day: 'Sun', successful: 6, failed: 0 },
    ],
    alerts: [
      { type: 'warning', message: 'Password expires in 18 days', severity: 'medium' },
      { type: 'info', message: 'New login from Windows Desktop', severity: 'low' },
    ],
  },

  // AUDIT LOGS PAGE
  auditLogs: [
    { timestamp: '2024-12-04 09:34', user: 'john.anderson', action: 'Login', database: 'CustomerDB', result: 'Success', ipAddress: '192.168.1.100', device: 'MacBook Pro' },
    { timestamp: '2024-12-04 10:12', user: 'john.anderson', action: 'Data Export', database: 'AnalyticsDB', result: 'Success', ipAddress: '192.168.1.100', device: 'MacBook Pro' },
    { timestamp: '2024-12-04 11:02', user: 'john.anderson', action: 'Query Execution', database: 'BillingDB', result: 'Success', ipAddress: '192.168.1.100', device: 'MacBook Pro' },
    { timestamp: '2024-12-04 14:30', user: 'john.anderson', action: 'Profile Update', database: '-', result: 'Success', ipAddress: '192.168.1.100', device: 'MacBook Pro' },
    { timestamp: '2024-12-03 16:45', user: 'john.anderson', action: 'Access Request', database: 'BillingDB', result: 'Pending', ipAddress: '192.168.1.100', device: 'MacBook Pro' },
    { timestamp: '2024-12-03 13:20', user: 'john.anderson', action: 'Login', database: 'CustomerDB', result: 'Success', ipAddress: '192.168.1.101', device: 'Windows Desktop' },
    { timestamp: '2024-12-02 08:15', user: 'john.anderson', action: 'Report Download', database: '-', result: 'Success', ipAddress: '10.0.0.50', device: 'Linux Server' },
  ],

  // NOTIFICATIONS PAGE
  notifications: [
    {
      id: 'notif-001',
      title: 'Access Request Approved',
      description: 'Your access request for BillingDB has been approved',
      timestamp: '2 hours ago',
      priority: 'high',
      category: 'Access Requests',
      read: false,
    },
    {
      id: 'notif-002',
      title: 'Database Maintenance Scheduled',
      description: 'CustomerDB maintenance on 2024-12-10 from 2-4 AM EST',
      timestamp: '1 day ago',
      priority: 'normal',
      category: 'Database Maintenance',
      read: false,
    },
    {
      id: 'notif-003',
      title: 'Security Alert: Successful Login',
      description: 'New device login detected: MacBook Pro from New York',
      timestamp: '2 days ago',
      priority: 'medium',
      category: 'Security Alerts',
      read: true,
    },
    {
      id: 'notif-004',
      title: 'Password Expiry Reminder',
      description: 'Your password expires in 18 days. Consider changing it',
      timestamp: '5 days ago',
      priority: 'medium',
      category: 'Security Alerts',
      read: true,
    },
    {
      id: 'notif-005',
      title: 'System Update Completed',
      description: 'Database Access Management system has been updated to v2.5.1',
      timestamp: '1 week ago',
      priority: 'low',
      category: 'System Updates',
      read: true,
    },
  ],

  // REPORTS PAGE
  reports: {
    stats: {
      generated: 24,
      downloads: 87,
      scheduled: 5,
      usageReports: 12,
    },
    reportTypes: [
      {
        id: 'report-001',
        name: 'Database Usage Report',
        description: 'Comprehensive database usage statistics and trends',
        lastGenerated: '2024-12-03',
        format: ['PDF', 'CSV'],
      },
      {
        id: 'report-002',
        name: 'Audit Activity Report',
        description: 'Detailed audit logs and user activity summary',
        lastGenerated: '2024-12-01',
        format: ['PDF', 'CSV', 'Excel'],
      },
      {
        id: 'report-003',
        name: 'Access History Report',
        description: 'Historical access requests and approvals',
        lastGenerated: '2024-11-28',
        format: ['PDF', 'CSV'],
      },
      {
        id: 'report-004',
        name: 'Security Activity Report',
        description: 'Security events and login patterns',
        lastGenerated: '2024-12-02',
        format: ['PDF', 'CSV'],
      },
    ],
    monthlyUsage: [
      { month: 'Aug', usage: 2400 },
      { month: 'Sep', usage: 2210 },
      { month: 'Oct', usage: 2290 },
      { month: 'Nov', usage: 2000 },
      { month: 'Dec', usage: 2500 },
    ],
    queryTrends: [
      { week: 'Week 1', queries: 1245 },
      { week: 'Week 2', queries: 1432 },
      { week: 'Week 3', queries: 1198 },
      { week: 'Week 4', queries: 1567 },
    ],
    dataAccessVolume: [
      { day: 'Mon', volume: 2.4 },
      { day: 'Tue', volume: 3.2 },
      { day: 'Wed', volume: 2.8 },
      { day: 'Thu', volume: 3.5 },
      { day: 'Fri', volume: 2.9 },
      { day: 'Sat', volume: 1.2 },
      { day: 'Sun', volume: 0.8 },
    ],
  },

  // PROFILE SETTINGS PAGE
  profileSettings: {
    personalInfo: {
      firstName: 'John',
      lastName: 'Anderson',
      employeeId: 'EMP-2024-001',
      email: 'john.anderson@company.com',
      phone: '+1 (555) 123-4567',
      department: 'Data Analytics',
      designation: 'Senior Data Analyst',
      currentRole: 'Database Analyst, Database Developer',
    },
    securitySettings: {
      mfaEnabled: true,
      mfaMethod: 'Authenticator App',
      passwordLastChanged: '2024-11-15',
      passwordExpires: '2025-02-15',
      twoFactorAuth: true,
    },
    trustedDevices: [
      { name: 'MacBook Pro', type: 'Mac', lastUsed: 'Today, 09:34 AM', trusted: true },
      { name: 'Windows Desktop', type: 'Windows', lastUsed: '2 days ago', trusted: true },
    ],
    recentLogins: [
      { timestamp: '2024-12-04 09:34', device: 'MacBook Pro', location: 'New York, USA', ipAddress: '192.168.1.100', status: 'Success' },
      { timestamp: '2024-12-03 13:20', device: 'Windows Desktop', location: 'New York, USA', ipAddress: '192.168.1.101', status: 'Success' },
      { timestamp: '2024-12-02 08:15', device: 'Linux Server', location: 'Cloud Datacenter', ipAddress: '10.0.0.50', status: 'Success' },
      { timestamp: '2024-12-01 15:45', device: 'iPhone', location: 'New York, USA', ipAddress: '192.168.1.50', status: 'Success' },
    ],
  },

  // HELP & SUPPORT PAGE
  supportData: {
    stats: {
      openTickets: 2,
      resolvedTickets: 18,
      avgResolutionTime: '4 hours',
    },
    faqs: [
      {
        question: 'How do I request access to a new database?',
        answer: 'Navigate to "Access Requests" page, click "Create New Request", select database, role, and provide business justification.',
      },
      {
        question: 'What does the access request approval process involve?',
        answer: 'Your manager reviews the request, verifies business need, then Security team approves based on policies. Typically takes 1-2 business days.',
      },
      {
        question: 'Can I export data from databases?',
        answer: 'Export capability depends on your assigned role. Database Analyst role allows read-only access with export permissions.',
      },
      {
        question: 'How often are passwords required to be changed?',
        answer: 'Passwords must be changed every 90 days per company security policy.',
      },
      {
        question: 'What should I do if I suspect unauthorized access?',
        answer: 'Contact Security team immediately at security@company.com or use the "Raise Support Ticket" form with priority "Critical".',
      },
    ],
    supportCategories: ['General Questions', 'Access Requests', 'Database Issues', 'Security', 'Technical Support'],
    tickets: [
      { id: 'TKT-001', subject: 'Cannot connect to ProductionDB', status: 'Open', created: '2024-12-03', resolved: null },
      { id: 'TKT-002', subject: 'Password reset needed', status: 'Open', created: '2024-12-02', resolved: null },
    ],
  },
}
