export const enterpriseDashboardData = {
  kpis: [
    {
      id: 'databases',
      title: 'Total Databases',
      value: 127,
      subtitle: '+12 this month',
      icon: 'database',
      color: 'blue',
      trend: 12,
    },
    {
      id: 'users',
      title: 'Active Users',
      value: 3842,
      subtitle: '+243 this month',
      icon: 'users',
      color: 'green',
      trend: 243,
    },
    {
      id: 'servers',
      title: 'Connected Servers',
      value: 54,
      subtitle: 'Healthy',
      icon: 'server',
      color: 'purple',
      trend: 0,
    },
    {
      id: 'data',
      title: 'Protected Data',
      value: 12.8,
      unit: 'TB',
      subtitle: '+1.2 TB growth',
      icon: 'shield',
      color: 'orange',
      trend: 1.2,
    },
    {
      id: 'queries',
      title: 'Queries Processed',
      value: 18.4,
      unit: 'M',
      subtitle: 'Today',
      icon: 'zap',
      color: 'cyan',
      trend: 0,
    },
    {
      id: 'alerts',
      title: 'Security Alerts',
      value: 23,
      subtitle: '7 Critical',
      icon: 'alert-triangle',
      color: 'red',
      trend: -2,
    },
    {
      id: 'requests',
      title: 'Access Requests',
      value: 54,
      subtitle: 'Requires Approval',
      icon: 'inbox',
      color: 'yellow',
      trend: 12,
    },
    {
      id: 'compliance',
      title: 'Compliance Score',
      value: 97,
      unit: '%',
      subtitle: 'Excellent',
      icon: 'check-circle',
      color: 'green',
      trend: 2,
    },
  ],

  databaseDistribution: [
    { name: 'PostgreSQL', value: 45, percentage: 35, fill: '#3b82f6' },
    { name: 'MySQL', value: 32, percentage: 25, fill: '#10b981' },
    { name: 'MongoDB', value: 19, percentage: 15, fill: '#f59e0b' },
    { name: 'Oracle', value: 15, percentage: 12, fill: '#ef4444' },
    { name: 'SQL Server', value: 13, percentage: 10, fill: '#8b5cf6' },
    { name: 'Others', value: 3, percentage: 3, fill: '#6b7280' },
  ],

  growthTrend: [
    { date: 'Jan 1', storage: 10.2, databases: 115, users: 3200 },
    { date: 'Jan 8', storage: 10.5, databases: 118, users: 3350 },
    { date: 'Jan 15', storage: 10.8, databases: 121, users: 3450 },
    { date: 'Jan 22', storage: 11.2, databases: 124, users: 3600 },
    { date: 'Jan 29', storage: 11.5, databases: 126, users: 3750 },
    { date: 'Feb 5', storage: 11.9, databases: 127, users: 3842 },
  ],

  queryMonitoring: [
    { time: '00:00', select: 1200, insert: 400, update: 300, delete: 100, failed: 45 },
    { time: '04:00', select: 800, insert: 200, update: 150, delete: 50, failed: 20 },
    { time: '08:00', select: 2400, insert: 1200, update: 800, delete: 300, failed: 150 },
    { time: '12:00', select: 3600, insert: 1800, update: 1200, delete: 400, failed: 220 },
    { time: '16:00', select: 3200, insert: 1600, update: 1000, delete: 350, failed: 180 },
    { time: '20:00', select: 2800, insert: 1400, update: 900, delete: 320, failed: 160 },
  ],

  topDatabasesByLoad: [
    { name: 'ProductionDB-01', cpu: 78, queries: 4500, connections: 284 },
    { name: 'AnalyticsDB-02', cpu: 65, queries: 3200, connections: 156 },
    { name: 'CacheDB-01', cpu: 52, queries: 2100, connections: 89 },
    { name: 'ReportDB-03', cpu: 48, queries: 1800, connections: 67 },
    { name: 'UserDB-01', cpu: 42, queries: 1200, connections: 52 },
  ],

  accessRequests: {
    pending: 54,
    approvedToday: 28,
    rejected: 12,
    escalated: 8,
  },

  recentActivities: [
    {
      id: '1',
      type: 'login',
      user: 'Alice Johnson',
      description: 'Logged in to admin dashboard',
      timestamp: '2 minutes ago',
      icon: 'log-in',
    },
    {
      id: '2',
      type: 'access',
      user: 'Bob Smith',
      description: 'Granted access to ProductionDB',
      timestamp: '5 minutes ago',
      icon: 'check-circle',
    },
    {
      id: '3',
      type: 'backup',
      user: 'System',
      description: 'Backup completed successfully',
      timestamp: '12 minutes ago',
      icon: 'save',
    },
    {
      id: '4',
      type: 'alert',
      user: 'Security',
      description: 'Failed login detected from unknown IP',
      timestamp: '18 minutes ago',
      icon: 'alert-triangle',
    },
    {
      id: '5',
      type: 'discovery',
      user: 'Admin',
      description: 'New MongoDB instance discovered',
      timestamp: '25 minutes ago',
      icon: 'database',
    },
    {
      id: '6',
      type: 'approval',
      user: 'Security Admin',
      description: 'Privileged access request approved',
      timestamp: '32 minutes ago',
      icon: 'check',
    },
    {
      id: '7',
      type: 'violation',
      user: 'System',
      description: 'Policy violation detected on Finance DB',
      timestamp: '45 minutes ago',
      icon: 'x-circle',
    },
  ],

  securityAlerts: [
    { category: 'Failed Login Attempts', count: 12, severity: 'high', color: 'red' },
    { category: 'Suspicious Queries', count: 8, severity: 'high', color: 'orange' },
    { category: 'Unauthorized Access', count: 5, severity: 'medium', color: 'yellow' },
    { category: 'Data Export Events', count: 3, severity: 'high', color: 'red' },
    { category: 'Privilege Escalation', count: 2, severity: 'critical', color: 'red' },
    { category: 'Malware Detection', count: 0, severity: 'low', color: 'blue' },
  ],

  healthStatus: [
    { name: 'Healthy', value: 98, fill: '#10b981' },
    { name: 'Warning', value: 18, fill: '#f59e0b' },
    { name: 'Critical', value: 4, fill: '#ef4444' },
  ],

  storageData: [
    { database: 'PostgreSQL', used: 4.2, capacity: 5 },
    { database: 'MySQL', used: 2.8, capacity: 4 },
    { database: 'MongoDB', used: 3.1, capacity: 4 },
    { database: 'Oracle', used: 1.8, capacity: 2.5 },
    { database: 'SQL Server', used: 0.9, capacity: 1.5 },
  ],

  dataGrowth: [
    { database: 'PostgreSQL', growth: 245, percentage: 32 },
    { database: 'MySQL', growth: 156, percentage: 28 },
    { database: 'MongoDB', growth: 189, percentage: 38 },
    { database: 'Oracle', growth: 78, percentage: 15 },
    { database: 'SQL Server', growth: 42, percentage: 12 },
  ],

  systemHealth: {
    cpu: 64,
    memory: 71,
    disk: 58,
    network: 45,
    apiLatency: 234,
    queryResponse: 128,
  },

  riskAssessment: {
    highRisk: 3,
    mediumRisk: 12,
    lowRisk: 112,
    riskScore: 28,
  },

  compliance: [
    { name: 'GDPR', score: 95, status: 'excellent' },
    { name: 'HIPAA', score: 92, status: 'excellent' },
    { name: 'SOC2', score: 94, status: 'excellent' },
    { name: 'ISO 27001', score: 97, status: 'excellent' },
  ],

  backupStatus: {
    successful: 89,
    failed: 2,
    lastBackup: '2 hours ago',
    storageUsed: '2.4 TB',
  },

  dataClassification: [
    { name: 'Public Data', value: 15, fill: '#6b7280' },
    { name: 'Internal Data', value: 35, fill: '#3b82f6' },
    { name: 'Confidential Data', value: 40, fill: '#8b5cf6' },
    { name: 'Restricted Data', value: 10, fill: '#ef4444' },
  ],

  geographicalData: [
    { region: 'US East', databases: 45, percentage: 35 },
    { region: 'US West', databases: 28, percentage: 22 },
    { region: 'Europe', databases: 32, percentage: 25 },
    { region: 'Asia', databases: 18, percentage: 14 },
    { region: 'Others', databases: 4, percentage: 3 },
  ],

  databaseInventory: [
    {
      name: 'ProductionDB-01',
      type: 'PostgreSQL',
      environment: 'Production',
      owner: 'Database Team',
      region: 'US East',
      status: 'Healthy',
      storage: '850GB',
      connections: 284,
      lastBackup: '2 hours ago',
    },
    {
      name: 'AnalyticsDB-02',
      type: 'MySQL',
      environment: 'Production',
      owner: 'Analytics Team',
      region: 'US East',
      status: 'Healthy',
      storage: '640GB',
      connections: 156,
      lastBackup: '4 hours ago',
    },
    {
      name: 'UserServiceDB',
      type: 'MongoDB',
      environment: 'Production',
      owner: 'Application Team',
      region: 'US West',
      status: 'Healthy',
      storage: '1.2TB',
      connections: 128,
      lastBackup: '3 hours ago',
    },
    {
      name: 'FinanceDB',
      type: 'Oracle',
      environment: 'Production',
      owner: 'Finance Team',
      region: 'Europe',
      status: 'Warning',
      storage: '950GB',
      connections: 89,
      lastBackup: '6 hours ago',
    },
    {
      name: 'HRSystem',
      type: 'SQL Server',
      environment: 'Production',
      owner: 'HR Team',
      region: 'US East',
      status: 'Healthy',
      storage: '480GB',
      connections: 64,
      lastBackup: '5 hours ago',
    },
    {
      name: 'CacheDB-01',
      type: 'Redis',
      environment: 'Production',
      owner: 'Platform Team',
      region: 'US East',
      status: 'Healthy',
      storage: '120GB',
      connections: 512,
      lastBackup: '1 hour ago',
    },
    {
      name: 'ReportDB-03',
      type: 'PostgreSQL',
      environment: 'Staging',
      owner: 'BI Team',
      region: 'Europe',
      status: 'Healthy',
      storage: '580GB',
      connections: 42,
      lastBackup: '8 hours ago',
    },
    {
      name: 'TestDB-QA',
      type: 'MySQL',
      environment: 'Testing',
      owner: 'QA Team',
      region: 'US West',
      status: 'Critical',
      storage: '320GB',
      connections: 28,
      lastBackup: '12 hours ago',
    },
  ],
}
